#!/bin/bash

SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
WORKDING_DIR="$(pwd)"
CURRENT_DIR=$(basename $(pwd))

CONTAINER_RUNTIME_NAME="$CURRENT_DIR-build"

docker run -it --rm \
    -v "$WORKDING_DIR":/opt/"$CURRENT_DIR" \
    -v "$WORKDING_DIR"/gradle:/root/.gradle/. \
    --name $CONTAINER_RUNTIME_NAME \
    -w /opt/"$CURRENT_DIR" \
    "$( "$SH_DIR/dev-image-tag" )" \
    yarn --cwd webapp/ run build && sh gradlew build
