#!/bin/bash

SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
WORKDING_DIR="$(pwd)"
CURRENT_DIR=$(basename $(pwd))

CONTAINER_RUNTIME_NAME="$CURRENT_DIR-test"

docker run -it --rm \
    -v "$WORKDING_DIR":/opt/"$CURRENT_DIR" \
    -v "$WORKDING_DIR"/gradle:/root/.gradle/. \
    --name $CONTAINER_RUNTIME_NAME \
    -p 8080:8080 \
    -p 8025:8025 \
    -p 3000:3000 \
    -w /opt/"$CURRENT_DIR" \
    "$( "$SH_DIR/dev-image-tag" )" \
    sh gradlew bootRun & yarn --cwd webapp/ run start & wait
