#!/bin/bash

WORKDING_DIR="$(pwd)"
CURRENT_DIR=$(basename $(pwd))

CONTAINER_RUNTIME_NAME="$CURRENT_DIR-test"

docker run -it --rm \
    -v "$WORKDING_DIR":/opt/"$CURRENT_DIR" \
    -v "$WORKDING_DIR"/gradle:/root/.gradle/. \
    --name $CONTAINER_RUNTIME_NAME \
    -p 8080:8080 \
    -p 8025:8025 \
    -w /opt/"$CURRENT_DIR" \
    amazoncorretto:17.0.6-al2023 \
    sh gradlew bootRun
