fakesmtp:
  webapp:
    authentication:
      enabled: true
      username: myuser
      password: mysecretpassword
      concurrent-sessions: 2
    session:
      session-timeout-minutes: ${FAKESMTP_WEBAPP_SESSION_TIMEOUT_MINUTES:2}
      sse-heartbeat-interval-seconds: ${FAKESMTP_WEBAPP_SSE_HEARTBEAT_INTERVAL_SECONDS:30}
      sse-event-send-timeout-seconds: ${FAKESMTP_WEBAPP_SSE_EVENT_SEND_TIMEOUT_SECONDS:5}
    rate-limiting:
      whitelist-localhost: true

logging:
  level:
    de.gessnerfl.fakesmtp.service.EmailSseEmitterService: DEBUG

spring:
  h2:
    console:
      enabled: true
