CREATE TABLE email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    from_address VARCHAR(255) NOT NULL,
    to_address VARCHAR(255) NOT NULL,
    subject TEXT NOT NULL,
    received_on TIMESTAMP NOT NULL,
    content TEXT NOT NULL
);

create sequence email_sequence start with 1 increment by 1;